// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shared.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

APIError _$APIErrorFromJson(Map<String, dynamic> json) => APIError(
      json['error_code'] as int,
      json['error_msg'] as String,
      (json['request_params'] as List<dynamic>)
          .map((e) => Map<String, String>.from(e as Map))
          .toList(),
      json['captcha_sid'] as String?,
      json['captcha_img'] as String?,
    );

Map<String, dynamic> _$APIErrorToJson(APIError instance) => <String, dynamic>{
      'error_code': instance.errorCode,
      'error_msg': instance.errorMessage,
      'request_params': instance.requestParams,
      'captcha_sid': instance.captchaSID,
      'captcha_img': instance.captchaUrl,
    };

User _$UserFromJson(Map<String, dynamic> json) => User(
      json['id'] as int,
      json['first_name'] as String,
      json['last_name'] as String,
      json['deactivated'] as String?,
      json['is_closed'] as bool,
      json['can_access_closed'] as bool,
      json['about'] as String?,
      json['activities'] as String?,
      json['bdate'] as String?,
      json['blacklisted'] as int?,
      json['blacklisted_by_me'] as int?,
      json['books'] as String?,
      json['can_post'] as int?,
      json['can_see_all_posts'] as int?,
      json['can_see_audio'] as int?,
      json['can_send_friend_request'] as int?,
      json['can_write_private_message'] as int?,
      json['career'],
      json['city'],
      json['common_count'] as int?,
      json['contacts'],
      json['country'],
      json['crop_photo'],
      json['domain'] as String?,
      json['education'],
      json['exports'],
      json['first_name_nom'] as String?,
      json['first_name_gen'] as String?,
      json['first_name_dat'] as String?,
      json['first_name_acc'] as String?,
      json['first_name_ins'] as String?,
      json['first_name_abl'] as String?,
      json['followers_count'] as int?,
      json['friend_status'] as int?,
      json['games'] as String?,
      json['has_mobile'] as int?,
      json['has_photo'] as int?,
      json['home_town'] as String?,
      json['interests'] as String?,
      json['is_favorite'] as int?,
      json['is_friend'] as int?,
      json['is_hidden_from_feed'] as int?,
      json['is_no_index'] as int?,
      json['last_name_nom'] as String?,
      json['last_name_gen'] as String?,
      json['last_name_dat'] as String?,
      json['last_name_acc'] as String?,
      json['last_name_ins'] as String?,
      json['last_name_abl'] as String?,
      json['last_seen'],
      json['lists'] as String?,
      json['maiden_name'] as String?,
      json['military'],
      json['movies'] as String?,
      json['music'] as String?,
      json['nickname'] as String?,
      json['occupation'],
      json['online'] as int?,
      json['personal'],
      json['photo_50'] as String?,
      json['photo_100'] as String?,
      json['photo_200_orig'] as String?,
      json['photo_200'] as String?,
      json['photo_400_orig'] as String?,
      json['photo_id'] as String?,
      json['photo_max'] as String?,
      json['photo_max_orig'] as String?,
      json['quoutes'] as String?,
      json['relatives'],
      json['relation'] as int?,
      json['schools'],
      json['screen_name'] as String?,
      json['sex'] as int?,
      json['site'] as String?,
      json['status'] as String?,
      json['timezone'] as num?,
      json['trending'] as int?,
      json['tv'] as String?,
      json['universities'],
      json['verified'] as int?,
      json['wall_default'] as String?,
    )
      ..connections = (json['connections'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(k, e as String),
      )
      ..counters = (json['counters'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(k, e as int),
      );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'id': instance.id,
      'first_name': instance.firstName,
      'last_name': instance.lastName,
      'deactivated': instance.deactivated,
      'is_closed': instance.isClosed,
      'can_access_closed': instance.canAccessClosed,
      'about': instance.about,
      'activities': instance.activities,
      'bdate': instance.bdate,
      'blacklisted': instance.blacklisted,
      'blacklisted_by_me': instance.blacklistedByMe,
      'books': instance.books,
      'can_post': instance.canPost,
      'can_see_all_posts': instance.canSeeAllPosts,
      'can_see_audio': instance.canSeeAudio,
      'can_send_friend_request': instance.canSendFriendRequest,
      'can_write_private_message': instance.canWritePrivateMessage,
      'career': instance.career,
      'city': instance.city,
      'common_count': instance.commonCount,
      'connections': instance.connections,
      'contacts': instance.contacts,
      'counters': instance.counters,
      'country': instance.country,
      'crop_photo': instance.cropPhoto,
      'domain': instance.domain,
      'education': instance.education,
      'exports': instance.exports,
      'first_name_nom': instance.firstNameNom,
      'first_name_gen': instance.firstNameGen,
      'first_name_dat': instance.firstNameDat,
      'first_name_acc': instance.firstNameAcc,
      'first_name_ins': instance.firstNameIns,
      'first_name_abl': instance.firstNameAbl,
      'followers_count': instance.followersCount,
      'friend_status': instance.friendStatus,
      'games': instance.games,
      'has_mobile': instance.hasMobile,
      'has_photo': instance.hasPhoto,
      'home_town': instance.homeTown,
      'interests': instance.interests,
      'is_favorite': instance.isFavorite,
      'is_friend': instance.isFriend,
      'is_hidden_from_feed': instance.isHiddenFromFeed,
      'is_no_index': instance.isNoIndex,
      'last_name_nom': instance.lastNameNom,
      'last_name_gen': instance.lastNameGen,
      'last_name_dat': instance.lastNameDat,
      'last_name_acc': instance.lastNameAcc,
      'last_name_ins': instance.lastNameIns,
      'last_name_abl': instance.lastNameAbl,
      'last_seen': instance.lastSeen,
      'lists': instance.lists,
      'maiden_name': instance.maidenName,
      'military': instance.military,
      'movies': instance.movies,
      'music': instance.music,
      'nickname': instance.nickname,
      'occupation': instance.occupation,
      'online': instance.online,
      'personal': instance.personal,
      'photo_50': instance.photo50,
      'photo_100': instance.photo100,
      'photo_200_orig': instance.photo200orig,
      'photo_200': instance.photo200,
      'photo_400_orig': instance.photo400orig,
      'photo_id': instance.photoID,
      'photo_max': instance.photoMax,
      'photo_max_orig': instance.photoMaxOrig,
      'quoutes': instance.quoutes,
      'relatives': instance.relatives,
      'relation': instance.relation,
      'schools': instance.schools,
      'screen_name': instance.screenName,
      'sex': instance.sex,
      'site': instance.site,
      'status': instance.status,
      'timezone': instance.timezone,
      'trending': instance.trending,
      'tv': instance.tv,
      'universities': instance.universities,
      'verified': instance.verified,
      'wall_default': instance.wallDefault,
    };

AudioThumbnails _$AudioThumbnailsFromJson(Map<String, dynamic> json) =>
    AudioThumbnails(
      json['width'] as int,
      json['height'] as int,
      json['photo_34'] as String?,
      json['photo_68'] as String?,
      json['photo_135'] as String?,
      json['photo_270'] as String?,
      json['photo_300'] as String?,
      json['photo_600'] as String?,
      json['photo_1200'] as String?,
    );

Map<String, dynamic> _$AudioThumbnailsToJson(AudioThumbnails instance) =>
    <String, dynamic>{
      'width': instance.width,
      'height': instance.height,
      'photo_34': instance.photo34,
      'photo_68': instance.photo68,
      'photo_135': instance.photo135,
      'photo_270': instance.photo270,
      'photo_300': instance.photo300,
      'photo_600': instance.photo600,
      'photo_1200': instance.photo1200,
    };

AudioPlaylist _$AudioPlaylistFromJson(Map<String, dynamic> json) =>
    AudioPlaylist(
      json['id'] as int,
      json['owner_id'] as int,
      json['type'] as int,
      json['title'] as String,
      json['description'] as String,
      json['subtitle'] as String?,
      json['count'] as int,
      json['access_key'] as String,
      json['followers'] as int,
      json['plays'] as int,
      json['create_time'] as int,
      json['update_time'] as int,
      json['genres'],
      json['is_following'] as bool,
      json['photo'] == null
          ? null
          : AudioThumbnails.fromJson(json['photo'] as Map<String, dynamic>),
      json['permissions'],
      json['subtitle_badge'] as bool,
      json['play_button'] as bool,
      json['album_type'] as String,
      json['meta'],
      json['exclusive'] as bool,
    );

Map<String, dynamic> _$AudioPlaylistToJson(AudioPlaylist instance) =>
    <String, dynamic>{
      'id': instance.id,
      'owner_id': instance.ownerID,
      'type': instance.type,
      'title': instance.title,
      'description': instance.description,
      'subtitle': instance.subtitle,
      'count': instance.count,
      'access_key': instance.accessKey,
      'followers': instance.followers,
      'plays': instance.plays,
      'create_time': instance.createTime,
      'update_time': instance.updateTime,
      'genres': instance.genres,
      'is_following': instance.isFollowing,
      'photo': instance.photo,
      'permissions': instance.permissions,
      'subtitle_badge': instance.subtitleBadge,
      'play_button': instance.playButton,
      'album_type': instance.albumType,
      'meta': instance.meta,
      'exclusive': instance.exclusive,
    };

AudioAlbum _$AudioAlbumFromJson(Map<String, dynamic> json) => AudioAlbum(
      json['id'] as int,
      json['title'] as String,
      json['owner_id'] as int,
      json['access_key'] as String,
      json['thumb'] == null
          ? null
          : AudioThumbnails.fromJson(json['thumb'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$AudioAlbumToJson(AudioAlbum instance) =>
    <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'owner_id': instance.ownerID,
      'access_key': instance.accessKey,
      'thumb': instance.thumb,
    };

Audio _$AudioFromJson(Map<String, dynamic> json) => Audio(
      id: json['id'] as int,
      ownerID: json['owner_id'] as int,
      artist: json['artist'] as String,
      title: json['title'] as String,
      duration: json['duration'] as int,
      subtitle: json['subtitle'] as String?,
      accessKey: json['access_key'] as String,
      ads: json['ads'],
      isExplicit: json['is_explicit'] as bool? ?? false,
      isFocusTrack: json['is_focus_track'] as bool?,
      isLicensed: json['is_licensed'] as bool?,
      isRestricted: json['content_restricted'] == null
          ? false
          : boolFromInt(json['content_restricted'] as int),
      shortVideosAllowed: json['short_videos_allowed'] as bool?,
      storiesAllowed: json['stories_allowed'] as bool?,
      storiesCoverAllowed: json['stories_cover_allowed'] as bool?,
      trackCode: json['track_code'] as String?,
      url: json['url'] as String,
      date: json['date'] as int,
      album: json['album'] == null
          ? null
          : AudioAlbum.fromJson(json['album'] as Map<String, dynamic>),
      lyricsID: json['lyrics_id'] as int?,
      albumID: json['album_id'] as int?,
      genreID: json['genre_id'] as int?,
    );

Map<String, dynamic> _$AudioToJson(Audio instance) => <String, dynamic>{
      'id': instance.id,
      'owner_id': instance.ownerID,
      'artist': instance.artist,
      'title': instance.title,
      'duration': instance.duration,
      'subtitle': instance.subtitle,
      'access_key': instance.accessKey,
      'ads': instance.ads,
      'is_explicit': instance.isExplicit,
      'is_focus_track': instance.isFocusTrack,
      'is_licensed': instance.isLicensed,
      'content_restricted': intFromBool(instance.isRestricted),
      'short_videos_allowed': instance.shortVideosAllowed,
      'stories_allowed': instance.storiesAllowed,
      'stories_cover_allowed': instance.storiesCoverAllowed,
      'track_code': instance.trackCode,
      'url': instance.url,
      'date': instance.date,
      'album': instance.album,
      'lyrics_id': instance.lyricsID,
      'album_id': instance.albumID,
      'genre_id': instance.genreID,
    };
