arb-dir: lib/l10n
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
use-escaping: true
required-resource-attributes: false
use-named-parameters: true
synthetic-package: false
