name: fluttervk
description: Экспериментальный, неофициальный клиент ВКонтакте, с открытым исходным кодом, построенный при помощи фреймворка Flutter, с поддержкой прослушивания музыки без необходимости приобретать подписку VK BOOM.
publish_to: 'none'
version: 0.4.22+2

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: 3.27.0-0.2.pre

dependencies:
  animations: ^2.0.8
  archive: ^3.6.1
  async: ^2.11.0
  audio_service:
    git:
      url: https://github.com/Zensonaton/audio_service.git
      path: audio_service
      ref: minor
  audio_session: ^0.1.18
  awesome_dio_interceptor: ^1.2.0
  cached_network_image: ^3.3.1
  cancellation_token: ^2.0.1
  collection: ^1.17.2
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  device_info_plus: ^11.1.1
  diacritic: ^0.1.5
  dio: ^5.5.0+1
  dio_http2_adapter: ^2.5.3
  dio_smart_retry: 6.0.0
  discord_rpc: ^0.0.2
  dynamic_color: ^1.6.9
  file: ^7.0.0
  file_picker: ^8.1.3
  firebase_analytics: ^11.3.6
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  fullscreen_window: ^1.0.4
  gap: ^3.0.1
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1
  humanize_duration: ^0.0.2
  install_plugin: ^2.1.0
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  just_audio_media_kit:
    git:
      url: https://github.com/Zensonaton/just_audio_media_kit.git
      ref: "529af19"
  local_notifier: ^0.1.5
  logger: ^2.0.2+1
  lottie: ^3.1.0
  material_color_utilities: any
  media_kit: ^1.1.10+1
  media_kit_libs_linux: ^1.1.3
  media_kit_libs_windows_audio: ^1.0.9
  msgpack_dart: ^1.0.1
  package_info_plus: ^8.0.0
  palette_generator: ^0.3.3+3
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.2.1
  queue: ^3.1.0+2
  responsive_builder: ^0.7.0
  riverpod_annotation: ^2.3.5
  scroll_to_index: ^3.0.1
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  smtc_windows: ^0.1.2
  string_similarity: ^2.0.0
  styled_text: ^8.1.0
  system_tray: ^2.0.3
  url_launcher: ^6.2.2
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.1.4
  window_manager: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.5.11
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon.ico
    - assets/icon.png
    - assets/images/
    - assets/audios/

