version: "3.8"

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      - TELEGRAM_LOCAL=Yes
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}

    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
      - "8082:8082"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - telegram-bot-api-data:/telegram-bot-api-data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  telegram-bot-api-data:
