name: Windows & Android release

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java and Flutter for Android
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android release
        run: flutter build apk --release

      - name: Publish in Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: build/app/outputs/flutter-apk/app-release.apk
          format: html
          message: |
            <b>🚧 Новый билд для #Android</b>.


  build_windows:
    needs: build_android
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Publish in Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: build\windows\x64\runner\Release\fluttervk.exe
          format: html
          message: |
            <b>🚧 Новый билд для #Windows</b>.
